'use client';

import { Check, Send, X } from 'lucide-react';

interface InquiryModalProps {
    title: string;
    isSubmitted: boolean;
    onClose: () => void;
    onSubmit: () => void;
}

export default function InquiryModal({ title, isSubmitted, onClose, onSubmit }: InquiryModalProps) {
    return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-4 backdrop-blur-sm" onClick={(event) => { if (event.target === event.currentTarget) onClose(); }}><div className="relative w-full max-w-md rounded-xl border border-neon-green/40 bg-navy-dark p-6 text-slate-100 shadow-2xl"><button onClick={onClose} className="absolute right-4 top-4 p-1 text-gray-400 hover:text-white" aria-label="Close"><X className="h-5 w-5" /></button>{isSubmitted ? <div className="space-y-3 py-6 text-center"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full border border-neon-green/50 bg-neon-green/20 text-neon-green"><Check className="h-6 w-6" /></div><h2 className="text-lg font-bold">บันทึกข้อมูลเรียบร้อยแล้ว</h2><p className="text-xs text-slate-300">เจ้าหน้าที่ฝ่ายวิศวกรรมแสงสว่างจะติดต่อกลับโดยเร็วที่สุดครับ</p><button onClick={onClose} className="mt-4 rounded bg-neon-green px-5 py-2 text-xs hover:bg-neon-green">ปิดหน้าต่าง</button></div> : <><div className="mb-4 flex items-center gap-2 text-neon-green"><Send className="h-5 w-5" /><h2 className="text-lg font-bold">{title}</h2></div><form onSubmit={(event) => { event.preventDefault(); onSubmit(); }} className="space-y-4 text-sm"><label className="block text-xs text-slate-300">ชื่อ - นามสกุล หรือ ชื่อบริษัท *<input required type="text" className="mt-1 w-full rounded border border-slate-700 bg-navy-dark px-3 py-2 text-white outline-none focus:border-neon-green" /></label><label className="block text-xs text-slate-300">เบอร์โทรศัพท์ติดต่อ *<input required type="tel" className="mt-1 w-full rounded border border-slate-700 bg-navy-dark px-3 py-2 text-white outline-none focus:border-neon-green" /></label><label className="block text-xs text-slate-300">ประเภทโรงงาน / พื้นที่ใช้งาน<select className="mt-1 w-full rounded border border-slate-700 bg-navy-dark px-3 py-2 text-white outline-none focus:border-neon-green"><option>คลังสินค้า / โกดัง (Warehouse)</option><option>โรงงานฝ่ายผลิต (Manufacturing Line)</option><option>ลานจอดรถ / พื้นที่ภายนอก (Outdoor / Yard)</option><option>สนามกีฬา / อาคารเอนกประสงค์</option></select></label><label className="block text-xs text-slate-300">รายละเอียดเพิ่มเติม<textarea rows={3} placeholder="ระบุขนาดพื้นที่ หรือประเภทโคมไฟที่ต้องการ..." className="mt-1 w-full rounded border border-slate-700 bg-navy-dark px-3 py-2 text-white outline-none focus:border-neon-green" /></label><div className="flex justify-end gap-3 pt-2"><button type="button" onClick={onClose} className="rounded px-4 py-2 text-xs text-slate-400 hover:text-white">ยกเลิก</button><button type="submit" className="rounded bg-neon-green px-5 py-2 text-xs font-medium text-white shadow transition hover:bg-neon-green">ส่งข้อมูล</button></div></form></>}</div></div>;
}
